apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-2
  labels:
    app: multitool-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool-2
  template:
    metadata:
      labels:
        app: multitool-2
    spec:
      containers:
        - image: wbitt/network-multitool
          imagePullPolicy: IfNotPresent
          name: network-multitool
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi